In [2]:
import torch
print(torch.__version__)

2.7.0


In [9]:
x = torch.empty(3, 3, dtype=torch.long) # Empty 3x3 Tensor
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [10]:
x = torch.ones(3, 3) # 3x3 Tensor of ones
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [4]:
x = torch.rand(3, 3, dtype=torch.double) # Random 3x3 Tensor
print(x)

tensor([[0.2974, 0.9091, 0.4779],
        [0.8316, 0.9610, 0.2925],
        [0.7015, 0.2892, 0.5892]], dtype=torch.float64)


In [7]:
x = torch.rand(3, 3)
y = torch.rand(3, 3)

z = x + y
print(z)

tensor([[0.3042, 0.8140, 0.9707],
        [1.3734, 0.9212, 0.9701],
        [1.3945, 1.3196, 0.5266]])


In [ ]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

y = x + 2
z = y * y * 3
out = z.mean()

out.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [11]:
class A:
    def __init__(self):
        self.n = 2

    def add(self, m):
        print('self is {0} @A.add'.format(self))
        self.n += m


class B(A):
    def __init__(self):
        self.n = 3

    def add(self, m):
        print('self is {0} @B.add'.format(self))
        super().add(m)
        self.n += 3

if __name__=="__main__":
		b = B()
		b.add(2)
		print(b.n)

self is <__main__.B object at 0x105b8d010> @B.add
self is <__main__.B object at 0x105b8d010> @A.add
8


In [14]:
import torch.nn as nn
import torch.nn.functional as F
 
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(784, 10) # 定义一个全连接层：输入维度 784，输出维度 10
 
    def forward(self, x):
        x = x.view(-1, 784) # 将输入 x 展平成 (batch_size, 784)
        x = self.fc1(x)
        return F.log_softmax(x, dim=1)
 
net = Net()
print(net)

Net(
  (fc1): Linear(in_features=784, out_features=10, bias=True)
)


In [15]:
import torch.nn as nn
net = nn.Sequential(
    nn.Linear(784, 10)
)
print(net)

Sequential(
  (0): Linear(in_features=784, out_features=10, bias=True)
)


In [16]:
import collections
import torch.nn as nn
net = nn.Sequential(collections.OrderedDict([
        ('fc1', nn.Linear(784, 10))
    ]))
print(net)

Sequential(
  (fc1): Linear(in_features=784, out_features=10, bias=True)
)


In [ ]:
import torch.nn
net = nn.ModuleList([nn.Linear(784, 10)])
# net.append(nn.Linear(256, 10)) # 可以添加新的层
# print(net[-1]) # 可以通过索引访问
print(net)

ModuleList(
  (0): Linear(in_features=784, out_features=10, bias=True)
)


In [ ]:
import torch.nn as nn
net = nn.ModuleDict({
    'fc1' : nn.Linear(784, 10)
})
# print(net['fc1']) # 访问特定层，字典索引
# print(net.fc1) # 访问特定层，成员索引
print(net)

Linear(in_features=784, out_features=10, bias=True)
ModuleDict(
  (fc1): Linear(in_features=784, out_features=10, bias=True)
)


In [ ]:
import torch
import torch.nn as nn


